### ISSUE TITLE
Issue with cb() on authenticate

### ISSUE THREAD

**Issue by cyphunk** [superfeedr/xmpp-server#14]
in server.js

``` js
    // On Connect event. When a client connects.
    server.on("connect", function(client) {
        // Allows the developer to authenticate users against anything they want.
        client.on("authenticate", function(opts, cb) {
            User.find(opts.jid, function(user) {
                if (user && user.attrs.password === opts.password)
                    cb();
                else
                    cb(new Error("Authentication failure"));
            });
        });
```

Using a simple local redis server the authentication would constantly fail until I changed the cb call to

``` js
                if (user && user.attrs.password === opts.password)
                    cb(null, user);
```

Now some clients succeed, others (pidgin) appear to not receive or properly parse the success response.

**Comment by julien51** [comment]
Hum. Sorry for the delay in getting back to you It looks like some API changed for @node-xmpp since we wrote this. Unfortunately, we don't have much time to maintain this anymore. Would you be interested in becoming the maintainer?
