### ISSUE TITLE
Installation step :  sudo npm install -g xmpp-server 

### ISSUE THREAD

**Issue by mulderp** [superfeedr/xmpp-server#2]
Hello,
when trying to run 

sudo npm install -g xmpp-server 

I get the following problem:

npm ERR! failed to fetch https://github.com/superfeedr/node-xmpp/tarball/c2s
npm ERR! error installing xmpp-server@0.0.1 Error: 400 { server: 'nginx/1.0.4',
npm ERR! error installing xmpp-server@0.0.1   date: 'Wed, 14 Sep 2011 13:00:38 GMT',
npm ERR! error installing xmpp-server@0.0.1   'content-type': 'text/html',
npm ERR! error installing xmpp-server@0.0.1   'content-length': '270',
npm ERR! error installing xmpp-server@0.0.1   connection: 'close' }
npm ERR! error installing xmpp-server@0.0.1     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:108:33)
npm ERR! error installing xmpp-server@0.0.1     at ClientRequest.emit (events.js:67:17)
npm ERR! error installing xmpp-server@0.0.1     at HTTPParser.onIncoming (http2.js:1197:9)
npm ERR! error installing xmpp-server@0.0.1     at HTTPParser.onHeadersComplete (http2.js:108:31)
npm ERR! error installing xmpp-server@0.0.1     at Socket.ondata (http2.js:1096:22)
npm ERR! error installing xmpp-server@0.0.1     at Socket._onReadable (net_legacy.js:689:27)
npm ERR! error installing xmpp-server@0.0.1     at IOWatcher.onReadable [as callback](net_legacy.js:177:10)
npm ERR! Error: 400 { server: 'nginx/1.0.4',
npm ERR!   date: 'Wed, 14 Sep 2011 13:00:38 GMT',
npm ERR!   'content-type': 'text/html',
npm ERR!   'content-length': '270',
npm ERR!   connection: 'close' }
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:108:33)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http2.js:1197:9)
npm ERR!     at HTTPParser.onHeadersComplete (http2.js:108:31)
npm ERR!     at Socket.ondata (http2.js:1096:22)
npm ERR!     at Socket._onReadable (net_legacy.js:689:27)
npm ERR!     at IOWatcher.onReadable [as callback](net_legacy.js:177:10)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.0.1
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "xmpp-server"
npm ERR! cwd /Users/pmu/projects/
npm ERR! node -v v0.5.4
npm ERR! npm -v 1.0.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pmu/projects/npm-debug.log
npm not ok

What could be wrong?

Cheers,

Patrick

**Comment by superfeedr** [comment]
Hum... looks like it's a temporary issue with github. We link to a custom tarball for node-xmpp... and it's hosted in GH. as soon as @astro can merge the C2S branch we won"t need this hack anymore...
