### ISSUE TITLE
Testing with Adium not Okay

### ISSUE THREAD

**Issue by alexstrat** [superfeedr/xmpp-server#5]
Hi guys,

I've just came across xmpp-server and hitten my first try with it. I wanted to test it against a simple jabber client, Adium, and I get some difficulties.. 

That's what I did :

First of all, in `server.js`, I've disactivated the authenticate part (i call `cb()` without any verification) and logged any try of authentication. I don't care about auth for my use..

I've launched my adium client and try to connect as, for instance, `foo@localhost` with password `bar`. Adium warns me about the fact that my connection is not encrypted, my auth log is hitten and I'm sure that the authenticate callback is called. 

But Adium remains in state _connecting_.

has someone any hints about it ?

**EDIT :** I forgot to mention that I also disactivated the _Roster_ and _Presence_ modules.

**Comment by superfeedr** [comment]
Yes. Adium is a bit excessive and wants the server to send an initial presence as well as a roster before considering the user connected. You may want to check that the server does indeed send those, but I dno't think it does.
Check with [Psi](http://psi-im.org/) that has XML logging.

**Comment by alexstrat** [comment]
Oh thanks for your answer. 

I understand. Actually, I forgot to mention – shame on me – I also disactivated the _Roster_ and _Presence_ modules : this can explain that !! Maybe it works with'em, but I won't try, because it's sufficient for my need without.

I'll try Psi, this could be really helpful ! thanks.
